GET http://localhost:8083/api/userinfo

###

GET http://localhost:8083/api/productsinfo/security

###

POST http://localhost:8083/api/login
Content-Type: application/json

{
        "emailid": "sendtosoumyajit@gmail.com",
        "password": "admin@123"
}


###

POST http://localhost:8083/api/userprofile
Content-Type: application/json

{
        "emailid": "sendtosoumyajit@gmail.com"
}

###

POST http://localhost:8083/api/registration
Content-Type: application/json

{
        "email": "inboxofsoumyajit@hotmail.com",
        "firstname": "Soumyajit",
        "lastname": "Mondal",
        "password": "Admin@123"
}

###


PUT http://localhost:8083/api/userupdate/sahmen@gmail.com
Content-Type: application/json

{
        "firstname": "Sammy",
        "lastname": "Gibson",
        "password": "Admin@123"
}

###

GET http://localhost:8083/api/send

###

POST http://localhost:8083/api/postreviews
Content-Type: application/json

{
        "username": "Hridya Mondal",
        "reviews": "Good Product",
        "ratings": "4",
        "reviewStatus": false
}

